# Generated by Django 4.2.5 on 2023-09-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_beautypersonalcare_brand_clothe_colour_electronics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='processor_type',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='screen_size',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='storage_capacity',
        ),
        migrations.RemoveField(
            model_name='sportsoutdoors',
            name='age_group',
        ),
        migrations.AddField(
            model_name='clothe',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='men', max_length=10),
        ),
        migrations.AddField(
            model_name='clothe',
            name='size',
            field=models.CharField(choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], default='xs', max_length=10),
        ),
        migrations.AddField(
            model_name='electronics',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10),
        ),
        migrations.CreateModel(
            name='ComputerAndPhone',
            fields=[
                ('electronics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.electronics')),
                ('screen_size', models.CharField(max_length=50)),
                ('processor_type', models.CharField(max_length=100)),
                ('storage_capacity', models.CharField(max_length=100)),
            ],
            bases=('shop.electronics',),
        ),
    ]
