# Generated by Django 4.2.5 on 2023-09-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_gender_delete_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('electronics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.electronics')),
            ],
            bases=('shop.electronics',),
        ),
        migrations.CreateModel(
            name='BeautyPersonalCareBrand',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.brand')),
            ],
            bases=('shop.brand',),
        ),
        migrations.CreateModel(
            name='ClotheBrand',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.brand')),
            ],
            bases=('shop.brand',),
        ),
        migrations.CreateModel(
            name='ComputerAndPhoneBrand',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.brand')),
            ],
            bases=('shop.brand',),
        ),
        migrations.CreateModel(
            name='ElectronicsBrand',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.brand')),
            ],
            bases=('shop.brand',),
        ),
        migrations.CreateModel(
            name='HomeLivingBrand',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.brand')),
            ],
            bases=('shop.brand',),
        ),
        migrations.CreateModel(
            name='SportsOutdoorsBrand',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.brand')),
            ],
            bases=('shop.brand',),
        ),
        migrations.CreateModel(
            name='ToysGamesBrand',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.brand')),
            ],
            bases=('shop.brand',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AddField(
            model_name='electronics',
            name='subCategory',
            field=models.CharField(choices=[('computer', 'Computer'), ('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('accessories', 'accessories')], default='small', max_length=50),
        ),
        migrations.AddField(
            model_name='electronics',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.electronicsbrand'),
        ),
    ]
