# Generated by Django 4.2.5 on 2023-09-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_beautypersonalcare_brand_clothe_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerAndPhoneBrand',
        ),
    ]
