# Generated by Django 4.2.5 on 2023-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_size_clothe_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotheSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='sizes',
        ),
        migrations.AddField(
            model_name='clothe',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='shop.clothesize'),
        ),
    ]
